---
- name: Include variables
  include_vars: "../../../inventory/vars.yml"

- name: Create directory for Grafana  and Prometheus volumes
  file:
    path: "{{item}}"
    state: directory
    recurse: true
    mode: '0755'
  with_items:
     - "{{grafana_volume_conf}}"
     - "{{grafana_volume_data}}"
     - "{{prometheus_volume_conf}}"

###GRAFANA
- name: Copy grafana.ini
  ansible.builtin.template:
    src: template/grafana.ini
    dest: "{{grafana_volume_conf}}"
    remote_src: false

- name: Pull Grafana-oss image 
  containers.podman.podman_image:
    name: docker.io/grafana/grafana-oss
    state: present
    force: true

- name: Run Grafana container
  containers.podman.podman_container:
    name: grafana
    image: docker.io/grafana/grafana-oss
    state: started
    restart_policy: always
    volumes:
      - "{{grafana_volume_conf}}/grafana.ini:/etc/grafana/grafana.ini:z"
      - "{{grafana_volume_data}}:/etc/grafana/data:z"
    ports:
      "3000:3000"
    expose:
      - 3000

##PROMETEUS
- name: Create Prometheus data dir
  become: true  
  ansible.builtin.file:
    path: "{{prometheus_volume_data}}"
    state: directory
    owner: "{{ prometheus_user_id }}"
    group: "{{ prometheus_user_id }}"
    mode: '0755'

- name: Copy prometheus conf file
  ansible.builtin.template:
    src: template/prometheus.yml
    dest: "{{prometheus_volume_conf}}"
    remote_src: false

- name: Pull prometheus image 
  containers.podman.podman_image:
    name: docker.io/prom/prometheus
    state: present
    force: true

- name: Run Prometheus container
  containers.podman.podman_container:
    name: prometheus
    image: docker.io/prom/prometheus
    state: started
    restart_policy: always
    volumes:
      - "{{prometheus_volume_conf}}/prometheus.yml:/etc/prometheus/prometheus.yml:z"
      - "{{prometheus_volume_data}}:/prometheus:z"
    ports:
      "9090:9090"
    expose:
      - 9090
    command: "--config.file /etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"