
def push (Map args) {
        def defaults = [
        registryUrl: "https://registry.hub.docker.com",
        image: "",
        pushLatest: true
    ]
    args = defaults + args
    docker.withRegistry(args.registryUrl, 'DockerHub-creds') {
        image.push()
        if (args.pushLatest) {
             image.push("latest")
        }
    }
    return "${image}:${args.tag}"
}


pipeline {

    agent any

    environment {
        DOCKER_IMAGE_NAME = 't0mx2as0/modulo_form'
        DOCKER_BUILD_TAG = "${env.BUILD_ID}"
        DOCKER_DIR: ".os4execrcise/webapp/app/"
    }

    def nameimage = "env.DOCKER_:IMAGE_NAME":"env.DOCKER_BUILD_TAG"
    
    stages {

        stage ('Build image') {
            
            steps{
                script { 
                    docker.build (nameimage, env.DOCKER_IMAGE_NAME env.DOCKER_DIR)
                    echo "image: ${nameimage}"
                }
            }

        }
        stage ('Push image') {
            steps{
                script {
                    push (image: build_image)
                }
            }

        }


    }




}
